In [1]:
import torch
import torch.nn as nn

# Binary classification

In [2]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8,1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.0048]], grad_fn=<SigmoidBackward0>)


# Regression 

In [3]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
  nn.Linear(11,8),
  nn.Linear(8,12),
  nn.Linear(12,4),
  nn.Linear(4,1)
)

output = model(input_tensor)
print(output)

tensor([[-0.5546]], grad_fn=<AddmmBackward0>)


# Multi Class Classification

In [4]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.0848, 0.5680, 0.0772, 0.2700]], grad_fn=<SoftmaxBackward0>)


c:\Users\Shadow\anaconda3\envs\env\Lib\site-packages\torch\nn\modules\module.py:1751: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
