In [1]:
import numpy as np

tree_census = np.load('./data/tree_census.npy')
print(tree_census.shape)

(1000, 4)


In [2]:
# Print the shapes of tree_census and new_trees
print(tree_census.shape)

(1000, 4)


In [12]:
new_trees = np.array([1212,227386,8,0]).reshape(1,4)

In [13]:
# Print the shapes of tree_census and new_trees
print(tree_census.shape, new_trees.shape)

# Add rows to tree_census which contain data for the new trees
updated_tree_census = np.concatenate((tree_census,new_trees))
print(updated_tree_census)

(1000, 4) (1, 4)
[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1199 227387     11      0]
 [  1210 227386      6      0]
 [  1212 227386      8      0]]


In [14]:
# Delete the stump diameter column from tree_census
tree_census_no_stumps = np.delete(tree_census, 3, axis=1)

# Save the indices of the trees on block 313879
private_block_indices = np.where(tree_census[:, 1] == 313879)

In [15]:
# Delete the stump diameter column from tree_census
tree_census_no_stumps = np.delete(tree_census, 3, axis=1)

# Save the indices of the trees on block 313879
private_block_indices = np.where(tree_census[:,1] == 313879)

# Delete the rows for trees on block 313879 from tree_census_no_stumps
tree_census_clean = np.delete(tree_census_no_stumps,private_block_indices,axis=0)

# Print the shape of tree_census_clean
print(tree_census_clean.shape)

(998, 3)
